name: Bump Version

on:
  workflow_run:
    workflows: ["Release Workspace Extractor"]
    types:
      - completed
permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --all --tags --prune

      - name: Get version from tag
        id: get_version
        run: |
          set -e
          VERSION=$(git tag --list | grep -E '^[vV]?[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?$' | sort -V | tail -n 1)
          VERSION=${VERSION#v}
          VERSION=${VERSION#V}

          if [[ -z "$VERSION" ]]; then
            echo "Error: No valid version tag found"
            exit 1
          fi

          echo "version=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash
      - name: Set Version
        run: |
          set -e
          echo "Current directory: $PWD" && ls -l
          echo "Updating pip file ${FILE_NAME} with version: ${NEW_VERSION}"
          find $(pwd) -name "${FILE_NAME}" -exec sh -c 'sed -i "s/__version__ = \".*\"/__version__ = \"${NEW_VERSION}\"/" "$1"' _ {} \;
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.version }}
          FILE_NAME: __version__.py
        working-directory: "${{ github.workspace }}/snowflake-data-validation"

      - name: Repository Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://__token__:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git config --get remote.origin.url

      - name: Update Version files
        shell: bash
        run: |
          set -e
          echo "Current directory: $(pwd)"
          echo "Listing files in the workspace:"
          ls -la

          echo "Searching for files to update..."
          find . -name "$FILE_NAME"

          echo "Updating $FILE_NAME files..."
          find . -name "$FILE_NAME" -exec sed -i "s/^__version__ = \".*\"/__version__ = \"${NEW_VERSION}\"/" {} \;

          echo "Updated files:"
          find . -name "$FILE_NAME" -exec sh -c 'echo "File: $1" && grep "__version__" $1' _ {} \;
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.version }}
          FILE_NAME: __version__.py

      - name: Create temporary branch
        id: git_branch
        run: |
          set -e
          set -o pipefail

          TEMP_BRANCH="bump-version-${{ steps.get_version.outputs.version }}"

          echo "Checking if branch $TEMP_BRANCH exists..."
          if git ls-remote --heads origin "$TEMP_BRANCH" | grep -q "$TEMP_BRANCH"; then
            echo "Branch $TEMP_BRANCH exists remotely. Deleting..."
            git push origin --delete "$TEMP_BRANCH"
          fi

          if git branch --list | grep -q "$TEMP_BRANCH"; then
            echo "Branch $TEMP_BRANCH exists locally. Deleting..."
            git branch -D "$TEMP_BRANCH" || echo "Branch $TEMP_BRANCH not found locally. Skipping deletion."
          fi

          echo "Creating new branch: $TEMP_BRANCH"
          git checkout -b "$TEMP_BRANCH"
          git status
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Commit and push changes
        shell: bash
        run: |
          set -e
          set -o pipefail

          git add . --verbose

          if git diff --cached --quiet; then
            echo "No changes to commit."
            git status
          else
            git commit -m "Release v${{ steps.get_version.outputs.version }}: Bump version files

            ✨ This commit updates version files after a successful release
            📦 Version bumped to: ${{ steps.get_version.outputs.version }}
            🤖 Auto-generated by release workflow

            Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
            git push origin "$TEMP_BRANCH"
            echo "Changes pushed to $TEMP_BRANCH."
            git status
            git log --oneline -1
          fi
        env:
          TEMP_BRANCH: ${{ steps.git_branch.outputs.TEMP_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
